config/routes.rb
Rails.application.routes.draw do
  resources :ads, except: [:edit, :update, :destroy]

  root to: 'ads#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
    KIND = ["offre", "demande"]

    validates :kind, :title, :body, :zipcode, :pseudo, :email, :phone, presence: true
    validates :price, numericality: {greater_than: 0}, allow_nil: true

    validates_each :email do |record, attr, value|
        record.errors.add( attr, "must be a valid email" ) unless value =~ /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\Z/i
    end

    validates_each :phone do |record, attr, value|
        record.errors.add( attr, "must be a valid french phone number" ) unless value =~ /\A(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}\Z/
    end

    validates_each :kind do |record, attr, value|
        record.errors.add( attr, "must be one of: #{KIND.join( ', ' )}" ) unless KIND.include? value
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
    def index
        @query = {}
        if params && params[ads_path]
            @query[:kind] = params[ads_path][:kind] unless params[ads_path][:kind].blank?
            @query[:title] = params[ads_path][:title] unless params[ads_path][:title].blank?
            @query[:pseudo] = params[ads_path][:pseudo] unless params[ads_path][:pseudo].blank?
        end
        @ads_number = Ad.count
        @ads = Ad.where(@query).order(created_at: :desc).page(params[:page] || 1)
    end

    def show
        @ad = Ad.find_by_id(params[:id])
    end

    def new
        @ad = Ad.new
    end

    def create
        @ad = Ad.new(params.require(:ad).permit(:kind, :title, :body, :zipcode, :pseudo, :email, :phone, :price))

        if @ad.valid?
            @ad.save

            redirect_to @ad
        else
            render 'new'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_ad.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="label label-default pull-right"><%= ad.kind %></span>

        <h3 class="panel-title">
            <%= link_to( ad ) do %>
                <%= ad.title %>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <% if ad.price %>
            <h2><%= format('%.2f', ad.price) %>€</h2>
        <% end %>
        <p>Code postal: <%= ad.zipcode %></p>
    </div>
</div>

app/views/ads/index.html.erb
<h1>Toutes les annonces</h1>

<% if @ads_number == 0 %>
    <p>Il n'y a aucune annonce pour le moment.</p>
    <p>
        <%= link_to(new_ad_path, class: ["btn", "btn-primary"]) do %>
            Soyez le premier à poster une annonce !
        <% end %>
    </p>
<% else %>
    <div class="row">
        <div class="col-sm-8">
            <% if @ads.empty? %>
                <p>Aucune annonce ne correspond à ces critères.</p>
                <p>
                    <%= link_to(ads_path, class: ["btn", "btn-primary"]) do %>
                        Effacer les critères
                    <% end %>
                </p>
            <% else %>
                <% @ads.each do |ad| %>
                    <%= render partial: 'ad', locals: {ad: ad} %>
                <% end %>
                <%= paginate @ads %>
            <% end %>
        </div>
        <div class="col-sm-4">
            <h4>Chercher par:</h4>
            <%= form_for ads_path, method: :get do |f| %>
                <div class="form-group">
                    <%= f.label :kind %>
                    <%= f.collection_radio_buttons(:kind, ["offre", "demande"], :to_s, :to_s, required: false, class: 'form-control') do |b| %>
                        <div class="radio">
                            <label>
                                <%= b.radio_button %> <%= b.label %>
                            </label>
                        </div>
                    <% end %>
                </div>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field(:title, label: "Titre de l'annonce", required: false, class: 'form-control') %>
                </div>
                <div class="form-group">
                    <%= f.label :pseudo %>
                    <%= f.text_field(:pseudo, label: "Pseudo", required: false, class: 'form-control') %>
                </div>
                <input type="reset" value="Effacer" class="btn btn-default" />
                <%= f.submit "Rechercher", class: 'btn btn-primary' %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/ads/new.html.erb
<h1>Déposer une annonce</h1>

<%= semantic_form_for @ad do |f| %>
    <%= f.inputs name: "Votre annonce" do %>
        <%= f.input(:kind, label: "Type d'annonce", as: :radio, collection: ["offre", "demande"]) %>
        <%= f.input(:title, label: "Titre de l'annonce") %>
        <%= f.input(:body, label: "Texte de l'annonce", input_html: {id: 'ad_body_', rows: 10, cols: 20}) %>
        <%= f.input(:price, label: "Prix (en €uros)", min: 0) %>
    <% end %>

    <%= f.inputs name: "Vos informations" do %>
        <%= f.input(:zipcode, label: "Code postal") %>
        <%= f.input(:pseudo, label: "Pseudo") %>
        <%= f.input(:email, label: "Email") %>
        <%= f.input(:phone, label: "Téléphone") %>
    <% end %>

    <%= f.actions do %>
        <%= f.action(:submit, as: :button, label: "Valider", button_html: {class: 'btn btn-primary'}) %>
        <%= f.action(:cancel, as: :link, label: "Annuler", button_html: {class: 'btn btn-default'}) %>
    <% end %>
<% end %>

app/views/ads/show.html.erb
<div class="row">
    <div class="col-sm-8">
        <%= link_to(ads_path) do %>
            <span class="glyphicon glyphicon-arrow-left"></span> Retour à la liste des offres
        <% end %>
        <span class="label label-default pull-right"><%= @ad.kind %></span>
        <h1><%= @ad.title %></h1>

        <% unless @ad.price.nil? %>
            <h2><%= format('%.2f', @ad.price) %>€</h2>
        <% end %>

        <h3>Description</h3>
        <p>
            <%= @ad.body %>
        </p>
        <h3>Localisation</h3>
        <p>Code postal: <%= @ad.zipcode %></p>
    </div>
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><%= @ad.pseudo %></h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Email</dt>
                    <dd><%= @ad.email %></dd>
                    <dt>Téléphone</dt>
                    <dd><%= @ad.phone %></dd>
                </dl>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Le petit bon coin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#boncoin-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span> <span class="icon-bar"></span>
            </button>
            <%= link_to(root_path, class: ["navbar-brand"]) do %>
                Le petit bon coin
            <% end %>
        </div>
        <div class="collapse navbar-collapse" id="boncoin-navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to(new_ad_url) do %>
                        Poster une annonce
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <%= yield %>
</div>
</body>
</html>